<h1>Contacts</h1>


<div class="row">
    <div class="col-xs-4">
        <form id="testFormId" action="<?php print $this->url->get("test/myFormSave") ?>" method="post" data-type="ajax">

            <div class="form-group">
                <label>Nombre</label>
                <?php echo $pcData['myform']->render("name"); ?>
                <div class="error-msg help-block animation-slideDown"></div>
            </div>


            <div class="form-group">
                <label>Telefono</label>
                <?php echo $pcData['myform']->render("telephone"); ?>
                <div class="error-msg help-block animation-slideDown"></div>
            </div>


            <div class="form-group">
                <input type="submit" value="Save" />
            </div>

        </form>
    </div>
</div>
