<h1>Contacts</h1>


<div class="row">
    <div class="col-xs-4">
        <form id="testFormId" action="<?php print $this->url->get("test/myFormSave") ?>" method="post" data-type="ajax">

            <p>
                <label>Name</label>
                <?php echo $pcData['myform']->render("name"); ?>
            </p>

            <p>
                <label>Telephone</label>
                <?php echo $pcData['myform']->render("telephone"); ?>
            </p>

            <p>
                <input type="submit" value="Save" />
            </p>

        </form>
    </div>
</div>
