
<nav class="navbar navbar-default navbar-fixed-top navbar-gradient navbar-styled" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- logo -->
      <a class="navbar-brand" href="<?php print $this->url->get() ?>"><img alt="" height="20" src="<?php print($this->url->get("img/latam-logo.png"))?>"/></a>     
    </div>
    <div class="collapse navbar-collapse animated fadeIn" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav animated fadeIn text15">
        
        <li class=""><a href="<?php print($this->url->get('')) ?>calendario"> Mi Calendario </a></li>
        <?php

        if($this->AccesoAcl->tienePermiso('vistadiaria', 'gestionqa')) { ?>

            <li class=""><a href="<?php print($this->url->get('')) ?>gestion/dia"> Agendamiento </a></li>

        <?php
          }
        ?>

        <?php

        if($this->AccesoAcl->tienePermiso('crearevento', 'actividad')) { ?>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b> Eventos </b> <span class="caret"></span></a>
              <ul id="login-dp" class="dropdown-menu">
                <li class=""><a href="<?php print($this->url->get('')) ?>evento/nuevo"> Nuevo Evento  </a></li>
                <li class=""><a href="javscript:void(0)" data-toggle="tooltip" data-placement="bottom" title="Proximamente"> Historial de acciones  </a></li>
              </ul>
            </li>

        <?php
        }
        ?>

        <li class=""><a href="javscript:void(0)" data-toggle="tooltip" data-placement="bottom" title="Proximamente"> Informes  </a></li>
        <li class=""><a href="javscript:void(0)" data-toggle="tooltip" data-placement="bottom" title="Proximamente"> Opciones  </a></li>
        <li class=""><a href="javscript:void(0)" id='searchop'>buscar</a></li>
        <li class=""><a href="javscript:void(0)" data-toggle="tooltip" data-placement="bottom" title="Proximamente"> Ayuda  </a></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="gi gi-user"></i><b> <?php print(utf8_encode($this->auth->getIdentity()['name']))?> </b> <span class="caret"></span></a>
            <ul id="login-dp" class="dropdown-menu">
                <li class=""><a href="<?php print($this->url->get($this->auth->getIdentity()['email'])) ?>"> Perfil  </a></li>
                <li class=""><a href="<?php print($this->url->get('logout')) ?>"> Salir  </a></li>
            </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>