$.fn.datepicker.dates['es'] = {
    days: ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
    daysShort: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"],
    daysMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa", "Do"],
    months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
    monthsShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
    today: "Hoy",
    clear: "Borrar",
    weekStart: 1,
    format: "dd/mm/yyyy"
};


$( "#datepicker" ).datepicker({
  language: 'es'
});
$('#datepicker').on("changeDate", function() {
    $('#fecha').val(
        $('#datepicker').datepicker('getFormattedDate')
    );
    var persona = $('#btnBloqueLibre').data('val').split("&")[1];
   	var fecha = 'fecha='+$('#fecha').val();
	$('#btnBloqueLibre').data('val',fecha+'&'+persona);
	console.log($('#btnBloqueLibre').data('val'));
});

$('#persona').change(function(event) {
    var fecha = $('#btnBloqueLibre').data('val').split("&")[0];
   	var persona = 'persona='+$('#persona').val();
	$('#btnBloqueLibre').data('val',fecha+'&'+persona);
	console.log($('#btnBloqueLibre').data('val'));	
});




