<div class="row">
    <div class="col-lg-12">
        <div class="filter-box row">
            <div class="col-xs-4"></div>

            <div class="col-xs-4">
                <div class="list-group-container my-group-container">
                    <div class="list-group list-group-custom list-group-horizontal">
                        <a href="<?php print($this->url->get('')) ?>gestion/dia" class="list-group-item active">
                            <div class="circle-calendar">
                                <i class="fa fa-list"></i>
                            </div>
                            Gestión Diaria
                        </a>
                        <a href="<?php print($this->url->get('')) ?>calendario" class="list-group-item">
                            <div class="circle-calendar">
                                <i class="fa fa-calendar-o"></i>
                            </div>
                            Vista Semanal</a>
                    </div>
                </div>
            </div>

            <div class="col-xs-4" style="height: 64px;">

            </div>
        </div>
    </div>
</div>

<header>
    <div class="year"><?php print date('Y',strtotime($pcData['today'])) ?></div>
    <div class="month"><?php print $this->config['dateES']['meses_full'][(int)date('m',strtotime($pcData['today']))-1] ?></div>
    <div class="day">
        <input type="text" value="<?php print $pcData['today'] ?>">
        <a href="<?php print $this->url->get()?>calendar/changeDay"
           data-action="<?php print $this->url->get()?>calendar/changeDay"
           data-val="dateChange=<?php print date("Y-m-d", strtotime($pcData['today']."-1 day")); ?>" class="prev fa fa-angle-left"></a>
        <a href="<?php print $this->url->get()?>calendar/changeDay"
           data-action="<?php print $this->url->get()?>calendar/changeDay"
           data-val="dateChange=<?php print date("Y-m-d", strtotime($pcData['today']."+1 day")); ?>" class="next fa fa-angle-right"></a>
        <a href="#" class="cal fa fa-calendar"></a>
    </div>

    <div class="switcher">
        <a href="javascript:void(0)" data-toggle="tooltip" title="Usted está viendo los eventos del <?php print date('Y-m-d',strtotime($pcData['today'])) ?>" class="active"><i class="fa fa-list"></i></a>
    </div>
</header>

<div class="calendar-container double-scroll">
    <table class="week-view">
    <tr>
        <th class="td-time">
            Bloques <br> <i class="fa fa-clock-o" style="color:gray;font-size: 15px;"></i>
        </th>

        <?php foreach($pcData['usersCalendar'] as $user) { ?>
            <th class="webcal-box"><span><?php print $user->name ?> </span> </th>
        <?php } ?>
    </tr>
    <?php foreach($pcData['day'] as $keyHora => $hora) {?>
        <tr>
            <td class="td-time">
                <?php print date('H:i',strtotime($keyHora)) ?>
            </td>
            <?php foreach($hora as $keyUser => $disponible) {?>
                <?php if(!isset($disponible['obj']) && !is_array($disponible) && $disponible == 0) {?>
                    <td class="event-disp">
                        <?php
                        if($this->AccesoAcl->tienePermiso('crearevento', 'actividad')) { ?>

                            <div class="btn-group  pull-right">
                                <a id="newEventBox"
                                   href="javascript:void(0)"
                                   action="<?php print $this->url->get("proyecto") ?>"
                                   base_url="<?php print $this->url->get("proyecto") ?>"
                                   data-fecha="<?php print $pcData['today'] ?>"
                                   data-hora="<?php print $keyHora ?>"
                                   data-user="<?php print $keyUser ?>"
                                   data-tecnologias="<?php print $pcData['tecnologiaDictionary'][$keyUser] ?>" >
                                    <i class="hi hi-collapse"></i>
                                </a>

                                <div id="<?php print "b-".$keyHora."-".$pcData['today']."-".$keyUser ?>" class="bubble-msg-new-event">

                                </div>

                            </div>

                        <?php
                            }
                        ?>

                    </td>
                <?php } else { ?>
                    <?php if( $disponible['status'] == 'disponible') { ?>
                        <?php if(isset($disponible['obj']->Actividad) && is_object($disponible['obj']->Actividad)) { ?>
                            <td class="event-container" rowspan="<?php print $disponible['rowspan'] ?>">
                                <div class="event">
                                    <div class="title" style="min-height: <?php print ($disponible['rowspan']*27)."px" ?>;"><?php print $disponible['obj']->Actividad->actv_descripcion_breve ?></div>
                                    <div class="details">
                                        <?php print(date('H:i',strtotime($disponible['obj']->dspn_hora))." - ".date('H:i',strtotime($disponible['obj']->dspn_hora." + ". $disponible['duracion'] ." minutes "))) ?>
                                        <div class="popup" style="min-height: <?php print ($disponible['rowspan']*27)."px" ?>;">
                                            <div class="title-pop"><?php print $disponible['obj']->Actividad->actv_descripcion_breve ?></div>
                                            <p style="text-align: left;"><?php print $disponible['obj']->Actividad->actv_descripcion_ampliada ?> <br>
                                                <strong>Participantes:</strong>
                                                <?php foreach($disponible['obj']->Actividad->UserActividad as $iter ) {
                                                    print($iter->Users->name.", ");
                                                } ?>
                                                <br>
                                                <strong>Cuando:</strong> <?php print $disponible['obj']->dspn_fecha." ".$disponible['obj']->dspn_hora ?> <br>
                                                <strong>Duración:</strong> <?php print $disponible['obj']->Actividad->actv_duracion_horas ?> Horas <br>
                                                <strong>Creado Por:</strong> <?php print($disponible['obj']->Actividad->creadopor->name); ?> <br>
                                                <strong>Estado:</strong> <?php print $disponible['obj']->Actividad->estado->nombre ?> <br>

                                                <?php

                                                if($this->AccesoAcl->tienePermiso('verperfilevento', 'actividad')) { ?>

                                                    <a href="<?php print $this->url->get("actividad/perfil/" . $disponible['obj']->Actividad->actv_id) ?>"
                                                       class="link-lighter"></a>

                                                    <?php
                                                }
                                                ?>
                                            </p>

                                        </div>
                                    </div>
                                </div>
                            </td>
                        <?php } else { ?>
                            <?php if($disponible['obj']->EstadoDisponibilidad->edsp_id == 1) { ?>
                                <td class="event-disp">
                                    <?php
                                    if($this->AccesoAcl->tienePermiso('crearevento', 'actividad')) { ?>
                                        <div class="btn-group  pull-right ">
                                            <a href="javascript:void(0)" data-toggle="dropdown" class="dropdown-toggle">
                                                <i class="hi hi-collapse"></i>
                                            </a>
                                            <ul class="dropdown-menu dropdown-custom text-left"
                                                style="min-width: 140px;">
                                                <li>
                                                    <a href="<?php print $this->url->get() ?>evento/nuevo"
                                                       data-action="<?php print $this->url->get() ?>evento/nuevo"
                                                       data-val="hora=<?php print $keyHora ?>&fecha=<?php print $pcData['today'] ?>&calendarUser=<?php print $pcData['calendarUser'] ?>"
                                                       data-ajax="false">Crear Evento</a>

                                                    <a href="javascript:void(0)">Bloquear</a>
                                                </li>
                                            </ul>
                                        </div>
                                        <?php
                                    }
                                    ?>
                                </td>
                            <?php } elseif($disponible['obj']->EstadoDisponibilidad->edsp_id == 3) { ?>
                                <td class="event-blocked">&nbsp;</td>
                            <?php } ?>

                        <?php } ?>
                    <?php } ?>
                <?php } ?>
            <?php } ?>
        </tr>
    <?php } ?>

</table>
</div>