<div class="row">
    <div class="col-lg-12">
        <div class="filter-box row">
            <div class="col-xs-4"></div>
            <div class="col-xs-4">

                <?php

                    if($this->AccesoAcl->tienePermiso('vistadiaria', 'gestionqa')) { ?>
                        <div class="list-group-container my-group-container">
                            <div class="list-group list-group-custom list-group-horizontal">
                                <a href="<?php print($this->url->get('')) ?>gestion/dia" class="list-group-item ">
                                    <div class="circle-calendar">
                                        <i class="fa fa-list"></i>
                                    </div>
                                    Gestión Diaria
                                </a>
                                <a href="<?php print($this->url->get('')) ?>calendario"
                                   class="list-group-item active">
                                    <div class="circle-calendar">
                                        <i class="fa fa-calendar-o"></i>
                                    </div>
                                    Vista Semanal</a>
                            </div>
                        </div>

                <?php
                }
                ?>

            </div>
            <div class="col-xs-4">

                <?php

                     if($this->AccesoAcl->tienePermiso('changecalendaruser', 'gestionqa')) { ?>

                        <form id="filterPersonaForm" action="<?php print($this->url->get("calendar/changeWeekByUser")) ?>" method="post" data-type="ajax">
                <div class="form-group row form-row my-chosen">
                    <div class="col-sm-12 select-daily" style="text-align: left;">
                        <select data-submit="true" id="persona" name="userCalendar" class="select-chosen" data-placeholder="Cambiar persona..." style="width: 250px;">
                            <option></option>
                            <?php foreach($pcData['users'] as $persona ) {?>
                                <option <?php print(isset($pcData['calendarUser']) && $pcData['calendarUser'] == $persona->id?'selected="selected"':'' )?> value="<?php print $persona->id ?>"><?php print $persona->name ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <input class="hidden" name="dateChange" value="<?php print date("Y-m-d", strtotime($pcData['today'])) ?>" >
                </div>
            </form>

                <?php
                    }
                ?>
            </div>
        </div>
    </div>
</div>

<header>
    <div class="year"><?php print date('Y',strtotime($pcData['today'])) ?></div>
    <div class="month"><?php print $this->config['dateES']['meses_full'][(int)date('m',strtotime($pcData['today']))-1] ?></div>
    <div class="day">
        <input type="text" value="<?php print $pcData['today'] ?>">
        <a href="<?php print $this->url->get()?>calendar/changeWeekByDay"
           data-action="<?php print $this->url->get()?>calendar/changeWeekByDay"
           data-val="dateChange=<?php print date("Y-m-d", strtotime($pcData['today']."-1 week")); ?>&userCalendar=<?php print($pcData['calendarUser']) ?>" class="prev fa fa-angle-left"></a>
        <a href="<?php print $this->url->get()?>calendar/changeWeekByDay"
           data-action="<?php print $this->url->get()?>calendar/changeWeekByDay"
           data-val="dateChange=<?php print date("Y-m-d", strtotime($pcData['today']."+1 week")); ?>&userCalendar=<?php print($pcData['calendarUser']) ?>" class="next fa fa-angle-right"></a>
        <a href="#" class="cal fa fa-calendar"></a>
    </div>

    <div class="switcher">
        <a href="javascript:void(0)" data-toggle="tooltip" title="Usted está viendo la vista semanal para un usuario" class="active"><i class="fa fa-calendar-o"></i></a>
    </div>
</header>

<table class="week-view">
    <tr>
        <th class="td-time">Bloques <br> <i class="fa fa-clock-o" style="color:gray;font-size: 15px;"></i> </th>
        <?php foreach($pcData['fechas'] as $fecha) { ?>
            <th>
                <?php print $this->config['dateES']['dias_full'][date('w',strtotime($fecha))]; ?> <br>
                <span><?php print date('d/m',strtotime($fecha)) ?> </span>
            </th>
        <?php } ?>
    </tr>
    <?php foreach($pcData['week'] as $keyHora => $hora) {?>
        <tr>
            <td class="td-time">
                <?php print date('H:i',strtotime($keyHora)) ?>
            </td>
            <?php foreach($hora as $keyFecha => $disponible) {?>
                <?php if(!isset($disponible['obj']) && !is_array($disponible) && $disponible == 0) {?>
                    <td class="event-disp">
                        <?php
                            if($this->AccesoAcl->tienePermiso('crearevento', 'actividad')) { ?>

                            <div class="btn-group  pull-right">
                                <a id="newEventBox"
                                   href="javascript:void(0)"
                                   action="<?php print $this->url->get("proyecto") ?>"
                                   data-fecha="<?php print $keyFecha ?>"
                                   data-hora="<?php print $keyHora ?>"
                                   data-user="<?php print $pcData['calendarUser'] ?>"
                                   data-tecnologias="<?php print $pcData['tecnologiasUser'] ?>" >
                                    <i class="hi hi-collapse"></i>
                                </a>

                                <div id="<?php print "b-".$keyHora."-".$keyFecha."-".$pcData['calendarUser'] ?>" class="bubble-msg-new-event">

                                </div>

                            </div>
                        <?php
                            }
                        ?>
                    </td>
                <?php } else { ?>
                    <?php if( $disponible['status'] == 'disponible') { ?>
                        <?php if(isset($disponible['obj']->Actividad) && is_object($disponible['obj']->Actividad)) { ?>
                            <td class="event-container" rowspan="<?php print $disponible['rowspan'] ?>">
                                <div class="event">
                                    <div class="title" style="min-height: <?php print ($disponible['rowspan']*27)."px" ?>;"><?php print $disponible['obj']->Actividad->actv_descripcion_breve ?></div>
                                    <div class="details">
                                        <?php print(date('H:i',strtotime($disponible['obj']->dspn_hora))." - ".date('H:i',strtotime($disponible['obj']->dspn_hora." + ". $disponible['duracion'] ." minutes "))) ?>
                                        <div class="popup" style = "min-height: <?php print ($disponible['rowspan']*82)."px" ?>;">
                                            <div class="title-pop"><?php print $disponible['obj']->Actividad->actv_descripcion_breve ?></div>
                                            <p style="text-align: left;"><?php print $disponible['obj']->Actividad->actv_descripcion_ampliada ?> <br>
                                                <strong>Participantes:</strong>
                                                <?php foreach($disponible['obj']->Actividad->UserActividad as $iter ) {
                                                    print($iter->Users->name.", ");
                                                } ?>
                                                <br>
                                                <strong>Proyecto:</strong> <?php print $disponible['obj']->Actividad->Proyecto->nombre ?> <br>
                                                <strong>Cuando:</strong> <?php print $disponible['obj']->dspn_fecha." ".$disponible['obj']->dspn_hora ?> <br>
                                                <strong>Duración:</strong> <?php print $disponible['duracion'] ?> Minutos <br>
                                                <strong>Creado Por:</strong> <?php print($disponible['obj']->Actividad->creadopor->name); ?> <br>
                                                <strong>Estado:</strong> <?php print $disponible['obj']->Actividad->estado->nombre ?> <br>

                                                <a  href="<?php print $this->url->get()?>GestionQa/getEventDetail"
                                                    data-action="<?php print $this->url->get()?>GestionQa/getEventDetail"
                                                    data-val="actv=<?php print $disponible['obj']->Actividad->actv_id ?>">
                                                </a>

                                            </p>

                                        </div>
                                    </div>
                                </div>
                            </td>
                        <?php } else { ?>
                            <?php if($disponible['obj']->EstadoDisponibilidad->edsp_id == 1) { ?>
                                <td class="event-disp">
                                    <?php
                                        if($this->AccesoAcl->tienePermiso('crearevento', 'actividad')) { ?>
                                            <div class="btn-group  pull-right ">
                                                <a href="javascript:void(0)" data-toggle="dropdown" class="dropdown-toggle">
                                                    <i class="hi hi-collapse"></i>
                                                </a>
                                                <ul class="dropdown-menu dropdown-custom text-left"
                                                    style="min-width: 140px;">
                                                    <li>
                                                        <a href="<?php print $this->url->get() ?>evento/nuevo"
                                                           data-action="<?php print $this->url->get() ?>evento/nuevo"
                                                           data-val="hora=<?php print $keyHora ?>&fecha=<?php print $keyFecha ?>&calendarUser=<?php print $pcData['calendarUser'] ?>"
                                                           data-ajax="false">Crear Evento</a>

                                                        <a href="javascript:void(0)">Bloquear</a>
                                                    </li>
                                                </ul>
                                            </div>
                                    <?php
                                        }
                                    ?>
                                </td>
                            <?php } elseif($disponible['obj']->EstadoDisponibilidad->edsp_id == 3) { ?>
                                <td class="event-blocked">&nbsp;</td>
                            <?php } ?>

                        <?php } ?>
                    <?php } ?>
                <?php } ?>
            <?php } ?>
        </tr>
    <?php } ?>

</table>
<div class="mobile-view">
    <dl>
        <dt><span>Lunes</span></dt>
        <dd>
            <ul>
                <li><i class="fa fa-clock-o"></i><span>08.00 - 09.00</span>Instalación de V.1</li>
                <li><i class="fa fa-clock-o"></i><span>07.00 - 08.00</span>Instalación de V.1</li>
                <li><i class="fa fa-clock-o"></i><span>10.00 - 11.00</span>Instalación de V.1</li>
                <li><i class="fa fa-clock-o"></i><span>15.00 - 14.00</span>Instalación de V.1</li>
                <li><i class="fa fa-clock-o"></i><span>16.00 - 27.00</span>Instalación de V.1</li>
            </ul>
        </dd>
        <dt><span>Martes</span></dt>
        <dd>
            <ul>
                <li><i class="fa fa-clock-o"></i><span>08.00 - 09.00</span>Instalación de V.1</li>
                <li><i class="fa fa-clock-o"></i><span>07.00 - 08.00</span>Instalación de V.1</li>
                <li><i class="fa fa-clock-o"></i><span>10.00 - 11.00</span>Instalación de V.1</li>
                <li><i class="fa fa-clock-o"></i><span>15.00 - 14.00</span>Instalación de V.1</li>
                <li><i class="fa fa-clock-o"></i><span>16.00 - 27.00</span>Instalación de V.1</li>
            </ul>
        </dd>
    </dl>
</div>