<div class="base-page">
	<section class="timetable" style="margin-top: 32px;">		
		<select class="filter">
			<option value="">Todos</option>
			<option value="">Instalación</option>
			<option value="">Interno</option>
			<option value="">Aprobados</option>
			<option value="">Cancelados</option>
		</select>
		<header>							
			<div class="year">2016</div>							
			<div class="month">JUNIO</div>							
			<div class="day">
				<input type="text" value="07/06/2016">
				<a href="#" class="prev fa fa-angle-left"></a>
				<a href="#" class="next fa fa-angle-right"></a>
				<a href="#" class="cal fa fa-calendar"></a>
			</div>
			
			<div class="switcher">
				<a href="javascript:void(0)" data-toggle="tooltip" title="Vista Mensual"><i class="fa fa-calendar"></i></a>
				<a href="javascript:void(0)" data-toggle="tooltip" title="Vista Semanal" class="active"><i class="fa fa-calendar-o"></i></a>
			</div>
		</header>
		<table class="week-view">
			<tr>
				<th class="td-time">&nbsp;</th>
				<th><span>06.06 </span>LUNES</th>
				<th><span>07.06 </span>MARTES</th>
				<th><span>08.06 </span>MIÉRCOLES</th>
				<th><span>09.06 </span>JUEVES</th>
				<th><span>10.06 </span>VIERNES</th>
				<th><span>11.06 </span>SÁBADO</th>
				<th><span>12.06 </span>DOMINGO</th>
			</tr>
			
			<tr>
				<td class="td-time">
					<i class="fa fa-clock-o"></i>08.00 
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">REP - SUBIDA AMBIENTE</div>
						<div class="details">
							08.00 - 09.00
							<div class="popup">
								<div class="title">REP - SUBIDA AMBIENTE</div>		
								<p style="text-align: left;">Se subirá versión en el ambiente de QA, realizar pruebas de esfuerzo. <br>
								<strong>Participantes:</strong> Miguel Jara, Miguel Diaz. <br>
								<strong>Duración:</strong> 1 hr <br>
								<strong>Prioridad:</strong> 5-Media <br>
								<strong>Creado Por:</strong> Carolina Perez <br>
								<strong>Estado:</strong> Aprobado <br>
								</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">[RE AGENDADO] Special Line - Carga Datos Beta</div>
						<div class="details">
							08.00 - 09.00
							<div class="popup text-left">
								<h1 class="title" style="min-height: 12px;font-size: 12px;"><b>[RE AGENDADO] Special Line - Carga Datos Beta</b></h1>
								<p><strong class="title">Descripción</strong><small>PRY-2016-0043048</small><br>
								<strong class="title">Status</strong><small>Esperando Aprobación</small><br>
								<strong class="title">Fecha</strong><small>Martes, 20 Mayo 2016</small><br>
								<strong class="title">Mas...</strong><small></small><br>
								</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td>&nbsp;</td>
				<td class="event-container">
					<div class="event">
						<div class="title">APROBADO SOLICITUD DE INSTALACIÓN EN PRODUCCIÓN EAR Y SCRIPT PROYECTO PIA</div>
						<div class="details">
							08.00 - 09.00
							<div class="popup">
								<div class="title">Radiation Oncology</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">[WIS] Configuración Hudson </div>
						<div class="details">
							08.00 - 09.00
							<div class="popup">
								<div class="title">Emergency Department</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			
			<tr>
				<td class="td-time"> 
					<i class="fa fa-clock-o"></i>09.00
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">WCBI - Actualización tablas</div>
						<div class="details">
							09.00 10.00
							<div class="popup">
								<div class="title">Immunology & Allergy</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td>&nbsp;</td>
				<td class="event-container">
					<div class="event">
						<div class="title">PARTE1 Line - Carga Datos BETA</div>
						<div class="details">
							09.00 10.00
							<div class="popup">
								<div class="title">Pain Management</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">APROBADO-INTALACIÓN</div>
						<div class="details">
							09.00 10.00
							<div class="popup">
								<div class="title">Emergency Department</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			
			<tr>
				<td class="td-time">
					<i class="fa fa-clock-o"></i>10.00
				</td>
				<td>&nbsp;</td>
				<td class="event-container">
					<div class="event">
						<div class="title">Habilitar Boton paso a BETA Integración Continua APOS</div>
						<div class="details">
							10.00 - 11.00
							<div class="popup">
								<div class="title">Immunology & Allergy</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">Instalación en Beta Allow me R8C3</div>
						<div class="details">
							10.00 - 11.00
							<div class="popup">
								<div class="title">Pain Management</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td>&nbsp;</td>
				<td class="event-container">
					<div class="event">
						<div class="title">REP - AGILE</div>
						<div class="details">
							10.00 - 11.00
							<div class="popup">
								<div class="title">Emergency Department</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>

				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>

			<tr>
				<td class="td-time">
					<i class="fa fa-clock-o"></i>11.00
				</td>
				<td>&nbsp;</td>
				<td class="event-container">
					<div class="event">
						<div class="title">PMHP - Paso a Servidor QA</div>
						<div class="details">
							11.00 - 12.00
							<div class="popup">
								<div class="title">Immunology & Allergy</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">[INTERNO] Integración continua </div>
						<div class="details">
							11.00 - 12.00
							<div class="popup">
								<div class="title">Pain Management</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">Revisión de Código</div>
						<div class="details">
							11.00 - 12.00
							<div class="popup">
								<div class="title">Emergency Department</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>

				<td>&nbsp;</td>

				<td>&nbsp;</td>

				<td>&nbsp;</td>
			</tr>

			<tr>
				<td class="td-time">
					<i class="fa fa-clock-o"></i>12.00
				</td>
				<td class="event-container">
					<div class="event">
						<div class="event-disabled">Almuerzo</div>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="event-disabled">Almuerzo</div>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="event-disabled">Almuerzo</div>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="event-disabled">Almuerzo</div>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="event-disabled">Almuerzo</div>
					</div>
				</td>
			</tr>

			<tr>
				<td class="td-time">
					<i class="fa fa-clock-o"></i>13.00 
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">REP - SUBIDA AMBIENTE</div>
						<div class="details">
							13.00 - 14.00
							<div class="popup">
								<div class="title">Pain Management</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">[RE AGENDADO] Special Line - Carga Datos Beta</div>
						<div class="details">
							13.00 - 14.00
							<div class="popup">
								<div class="title">Immunology & Allergy</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td>&nbsp;</td>
				<td class="event-container">
					<div class="event">
						<div class="title">APROBADO SOLICITUD DE INSTALACIÓN EN PRODUCCIÓN EAR Y SCRIPT PROYECTO PIA</div>
						<div class="details">
							13.00 - 14.00
							<div class="popup">
								<div class="title">Radiation Oncology</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">[WIS] Configuración Hudson </div>
						<div class="details">
							13.00 - 14.00
							<div class="popup">
								<div class="title">Emergency Department</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			
			<tr>
				<td class="td-time"> 
					<i class="fa fa-clock-o"></i>14.00
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">WCBI - Actualización tablas</div>
						<div class="details">
							14.00 - 15.00
							<div class="popup">
								<div class="title">Immunology & Allergy</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td>&nbsp;</td>
				<td class="event-container">
					<div class="event">
						<div class="title">PARTE1 Line - Carga Datos BETA</div>
						<div class="details">
							14.00 - 15.00
							<div class="popup">
								<div class="title">Pain Management</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">APROBADO-INTALACIÓN</div>
						<div class="details">
							14.00 - 15.00
							<div class="popup">
								<div class="title">Emergency Department</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			
			<tr>
				<td class="td-time">
					<i class="fa fa-clock-o"></i>15.00
				</td>
				<td>&nbsp;</td>
				<td class="event-container">
					<div class="event">
						<div class="title">Habilitar Boton paso a BETA Integración Continua APOS</div>
						<div class="details">
							15.00 - 16.00
							<div class="popup">
								<div class="title">Immunology & Allergy</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">Instalación en Beta Allow me R8C3</div>
						<div class="details">
							15.00 - 16.00
							<div class="popup">
								<div class="title">Pain Management</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td>&nbsp;</td>
				<td class="event-container">
					<div class="event">
						<div class="title">REP - AGILE</div>
						<div class="details">
							15.00 - 16.00
							<div class="popup">
								<div class="title">Emergency Department</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>

				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>

			<tr>
				<td class="td-time">
					<i class="fa fa-clock-o"></i>16.00
				</td>
				<td>&nbsp;</td>
				<td class="event-container">
					<div class="event">
						<div class="title">PMHP - Paso a Servidor QA</div>
						<div class="details">
							16.00 - 17.00
							<div class="popup">
								<div class="title">Immunology & Allergy</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">[INTERNO] Integración continua </div>
						<div class="details">
							16.00 - 17.00
							<div class="popup">
								<div class="title">Pain Management</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">Revisión de Código</div>
						<div class="details">
							16.00 - 17.00
							<div class="popup">
								<div class="title">Emergency Department</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>

				<td>&nbsp;</td>

				<td>&nbsp;</td>

				<td>&nbsp;</td>
			</tr>


			<tr>
				<td class="td-time">
					<i class="fa fa-clock-o"></i>17.00
				</td>
				<td>&nbsp;</td>
				<td class="event-container">
					<div class="event">
						<div class="title">PMHP - Paso a Servidor QA</div>
						<div class="details">
							17.00 - 18.00
							<div class="popup">
								<div class="title">Immunology & Allergy</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">[INTERNO] Integración continua </div>
						<div class="details">
							17.00 - 18.00
							<div class="popup">
								<div class="title">Pain Management</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>
				<td class="event-container">
					<div class="event">
						<div class="title">Revisión de Código</div>
						<div class="details">
							17.00 - 18.00
							<div class="popup">
								<div class="title">Emergency Department</div>		
								<p>Presenter: Three people will speak about what you need, why you need them, and ways to organize your documents so others can access them. Join these panelists: Jill C. Jensen, LCSW, CMC, Care Manager at Gaylord</p>
								<a href="#"><span></span></a>
							</div>
						</div>
						<a href="#"><span></span></a>
					</div>
				</td>

				<td>&nbsp;</td>

				<td>&nbsp;</td>

				<td>&nbsp;</td>

			</tr>
		</table>
		<div class="mobile-view">
			<dl>
				<dt><span>Lunes</span></dt>
				<dd>
					<ul>
						<li><i class="fa fa-clock-o"></i><span>08.00 - 09.00</span>Instalación de V.1</li>
						<li><i class="fa fa-clock-o"></i><span>07.00 - 08.00</span>Instalación de V.1</li>
						<li><i class="fa fa-clock-o"></i><span>10.00 - 11.00</span>Instalación de V.1</li>
						<li><i class="fa fa-clock-o"></i><span>15.00 - 14.00</span>Instalación de V.1</li>
						<li><i class="fa fa-clock-o"></i><span>16.00 - 27.00</span>Instalación de V.1</li>
					</ul>
				</dd>
				<dt><span>Martes</span></dt>
				<dd>
					<ul>
						<li><i class="fa fa-clock-o"></i><span>08.00 - 09.00</span>Instalación de V.1</li>
						<li><i class="fa fa-clock-o"></i><span>07.00 - 08.00</span>Instalación de V.1</li>
						<li><i class="fa fa-clock-o"></i><span>10.00 - 11.00</span>Instalación de V.1</li>
						<li><i class="fa fa-clock-o"></i><span>15.00 - 14.00</span>Instalación de V.1</li>
						<li><i class="fa fa-clock-o"></i><span>16.00 - 27.00</span>Instalación de V.1</li>
					</ul>
				</dd>
			</dl>
		</div>
	</section>
</div>