<div class="base-page">
    <section class="timetable timetable-daily" style="margin-top: 32px;">
        <select class="filter">
            <option value="">Todos</option>
            <option value="">Instalación</option>
            <option value="">Interno</option>
            <option value="">Aprobados</option>
            <option value="">Cancelados</option>
        </select>

        <header>
            <div class="year">2014</div>
            <div class="month">October</div>
            <div class="day">
                <input type="text" value="10/10/13">
                <a href="#" class="prev fa fa-angle-left"></a>
                <a href="#" class="next fa fa-angle-right"></a>
                <a href="#" class="cal fa fa-calendar"></a>
            </div>

            <div class="switcher">
                <a href="timetable-month.html"><i class="fa fa-calendar"></i></a>
                <a href="timetable-week.html"><i class="fa fa-calendar-o"></i></a>
                <a href="timetable-list.html" class="active"><i class="fa fa-list"></i></a>
            </div>
        </header>

        <table class="list-view list-view-alt">
            <tr>
                <td>
                    <div>
                        <i class="fa fa-clock-o"></i>08.00 - 09.00
                    </div>
                </td>
                <td class="event-container">
                    <div class="event">
                        <div class="row row-disable">
                            <?php for($i=0; $i<18; $i++) {?>
                                <div class="col-xs-2 event-daily">
                                    <a  href="<?php print $this->url->get()?>GestionQa/getEventDetail"
                                        data-action="<?php print $this->url->get()?>GestionQa/getEventDetail"
                                        data-val="actv=1">
                                    <div class="event-tit">REP - SUBIDA AMBIENTE</div>
                                    </a>
                                </div>
                            <?php } ?>
                        </div>
                        <div class="row row-disable">
                            <div class="col-xs-2 event-daily new-event">
                                <a  href="javascript:void(0)"
                                    data-action=""
                                    data-val="">
                                    <div class="event-tit"><i class="gi gi-plus icon-daily"></i>  Nuevo</div>
                                </a>
                            </div>
                        </div>

                    </div>
                </td>
            </tr>

            <tr>
                <td>
                    <i class="fa fa-clock-o"></i>09:00 PM
                </td>
                <td class="event-container">
                    <div class="event">
                        <div class="row row-disable">
                            <?php for($i=0; $i<8; $i++) {?>
                                <div class="col-xs-2 event-daily">
                                    <div class="event-tit">REP - SUBIDA AMBIENTE</div>
                                </div>
                            <?php } ?>
                        </div>
                        <div class="row row-disable">
                            <div class="col-xs-2 event-daily new-event">
                                <a  href="javascript:void(0)"
                                    data-action=""
                                    data-val="">
                                    <div class="event-tit"><i class="gi gi-plus icon-daily"></i>  Nuevo</div>
                                </a>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>

            <tr>
                <td>
                    <i class="fa fa-clock-o"></i>10:00 PM
                </td>
                <td class="event-container">
                    <div class="event">
                        <div class="row row-disable">
                            <?php for($i=0; $i<11; $i++) {?>
                                <div class="col-xs-2 event-daily">
                                    <div class="event-tit">REP - SUBIDA AMBIENTE</div>
                                </div>
                            <?php } ?>
                        </div>
                        <div class="row row-disable">
                            <div class="col-xs-2 event-daily new-event">
                                <a  href="javascript:void(0)"
                                    data-action=""
                                    data-val="">
                                    <div class="event-tit"><i class="gi gi-plus icon-daily"></i>  Nuevo</div>
                                </a>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <i class="fa fa-clock-o"></i>13:00 PM
                </td>
                <td class="event-container">
                    <div class="event">
                        <div class="row row-disable">
                            <?php for($i=0; $i<2; $i++) {?>
                                <div class="col-xs-2 event-daily">
                                    <div class="event-tit">REP - SUBIDA AMBIENTE</div>
                                </div>
                            <?php } ?>
                        </div>
                        <div class="row row-disable">
                            <div class="col-xs-2 event-daily new-event">
                                <a  href="javascript:void(0)"
                                    data-action=""
                                    data-val="">
                                    <div class="event-tit"><i class="gi gi-plus icon-daily"></i>  Nuevo</div>
                                </a>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <i class="fa fa-clock-o"></i>14:00 PM
                </td>
                <td class="event-container">
                    <div class="event">
                        <div class="row row-disable">
                            <?php for($i=0; $i<8; $i++) {?>
                                <div class="col-xs-2 event-daily">
                                    <div class="event-tit">REP - SUBIDA AMBIENTE</div>
                                </div>
                            <?php } ?>
                        </div>
                        <div class="row row-disable">
                            <div class="col-xs-2 event-daily new-event">
                                <a  href="javascript:void(0)"
                                    data-action=""
                                    data-val="">
                                    <div class="event-tit"><i class="gi gi-plus icon-daily"></i>  Nuevo</div>
                                </a>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>

            <tr>
                <td>
                    <i class="fa fa-clock-o"></i>15:00 PM
                </td>
                <td class="event-container">
                    <div class="event">
                        <div class="row row-disable">
                            <?php for($i=0; $i<5; $i++) {?>
                                <div class="col-xs-2 event-daily">
                                    <div class="event-tit">REP - SUBIDA AMBIENTE</div>
                                </div>
                            <?php } ?>
                        </div>
                        <div class="row row-disable">
                            <div class="col-xs-2 event-daily new-event">
                                <a  href="javascript:void(0)"
                                    data-action=""
                                    data-val="">
                                    <div class="event-tit"><i class="gi gi-plus icon-daily"></i>  Nuevo</div>
                                </a>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>

            <tr>
                <td>
                    <i class="fa fa-clock-o"></i>16:00 PM
                </td>
                <td class="event-container">
                    <div class="event">
                        <div class="row row-disable">
                            <?php for($i=0; $i<5; $i++) {?>
                                <div class="col-xs-2 event-daily">
                                    <div class="event-tit">REP - SUBIDA AMBIENTE</div>
                                </div>
                            <?php } ?>
                        </div>
                        <div class="row row-disable">
                            <div class="col-xs-2 event-daily new-event">
                                <a  href="javascript:void(0)"
                                    data-action=""
                                    data-val="">
                                    <div class="event-tit"><i class="gi gi-plus icon-daily"></i>  Nuevo</div>
                                </a>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        </table>
    </section>
</div>

<div id="modal-data" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" style="padding-right: 0px !important;">
</div>