<div class="base-page lighter">
    <div class="list-group-container">
        <div class="list-group list-group-custom list-group-horizontal">
            <a href="#" class="list-group-item active">Detalle y Participantes</a>
            <a href="#" class="list-group-item">Repetición</a>
        </div>
    </div>
    <div class="formulario-section">
        <form id="evento-form" action="" method="post" data-type="ajax">
            <div class="row">
                <div class="col-sm-5">
                    <div class="form-content">
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="dscr-breve">Descripción Breve</label>
                            <div class="col-sm-8">
                                <input type="text" id="dscr-breve" name="dscr-breve" class="form-control input-sm" placeholder="Descripción Breve">
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="dscr-ampliada">Descripción Ampliada</label>
                            <div class="col-sm-8">
                                <textarea id="dscr-ampliada" name="dscr-ampliada" rows="5" class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="donde">¿Dónde?</label>
                            <div class="col-sm-8">
                                <input type="text" id="donde" name="donde" class="form-control input-sm" placeholder="Descripción Breve">
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="categoria">Categoría</label>
                            <div class="col-sm-8">
                                <select id="categoria" name="categoria" class="select-chosen my-chosen" data-placeholder="Elegir Categorías" style="width: 250px;" multiple>
                                    <option value="United States">Instalación</option>
                                    <option value="United Kingdom">Revisión</option>
                                    <option value="Afghanistan">Configurar</option>
                                    <option value="Aland Islands">Prueba</option>
                                    <option value="Aland Islands">Prueba Stress</option>
                                    <option value="Aland Islands">Prueba Integración</option>
                                    <option value="Aland Islands">Prueba Usabilidad</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="acceso">Acceso</label>
                            <div class="col-sm-8" style="text-align: left;">
                                <select id="acceso" name="acceso" class="select-chosen my-chosen" data-placeholder="Seleccionar..." style="width: 250px;">
                                    <option></option>
                                    <option value="1">privado</option>
                                    <option value="2">publico</option>
                                    <option value="3">Otra</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row form-row my-chosen">
                            <label class="col-sm-4 control-label" for="acceso">Prioridad</label>
                            <div class="col-sm-8" style="text-align: left;">
                                <select id="acceso" name="acceso" class="select-chosen" data-placeholder="Seleccionar..." style="width: 250px;">
                                    <option></option>
                                    <option value="1">Bajo-1</option>
                                    <option value="2">Bajo-2</option>
                                    <option value="3">Medio-1</option>
                                    <option value="3">Medio-2</option>
                                    <option value="3">Alto-1</option>
                                    <option value="3">Alto-2</option>
                                    <option value="3">Alto-2</option>
                                    <option value="3">Alto-2</option>
                                    <option value="3">Alto-2</option>
                                    <option value="3">Alto-2</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group row form-row">
                        <div class="">
                            <input type="text" id="fecha" name="fecha" class="form-control hidden input-datepicker" data-date-format="dd/mm/yy" placeholder="dd/mm/yy">
                            <div id="example-datepicker-inline" class="input-datepicker"></div>
                        </div>
                    </div>
                    <div class="form-group row form-row">
                        <div class="input-group bootstrap-timepicker" style="padding-left: 0px;">
                            <input style="margin-left:15px;" type="text" id="hora" name="hora" class="form-control input-timepicker24">
                            <span class="input-group-btn">
                                <a href="javascript:void(0)" class="btn btn-primary"><i class="fa fa-clock-o"></i></a>
                            </span>
                        </div>
                    </div>
                    <div class="form-group row form-row">
                        <label class="col-sm-12 control-label" for="duracion">Duración (Horas)</label>
                        <div class="col-sm-12">
                            <input type="Number" id="duracion" name="duracion" class="form-control input-sm" placeholder="Duración">
                        </div>
                    </div>
                    <div class="form-group row" style="text-align: center;">
                        <a href="javascript:void(0)" class="">Encontrar Bloque Libre</a>
                    </div>
                </div>
                <div class="col-sm-5">
                    <div class="form-content">
                        <div class="form-group row form-row my-chosen">
                            <label class="col-sm-12 control-label" for="acceso">Añadir Persona</label>

                            <div class="col-sm-8" style="text-align: left;">
                                <select id="acceso" name="acceso" class="select-chosen" data-placeholder="Seleccionar..." style="width: 250px;">
                                    <option></option>
                                    <option value="1">Cociña, Jorge</option>
                                    <option value="2">San Martìn, Orlando</option>
                                    <option value="3">Silva, Jorge</option>
                                    <option value="3">Silva, Sebastián</option>
                                    <option value="3">Silva, Sebastián</option>
                                    <option value="3">Silva, Sebastián</option>
                                    <option value="3">Silva, Sebastián</option>
                                    <option value="3">Silva, Sebastián</option>
                                    <option value="3">Silva, Sebastián</option>
                                </select>
                            </div>

                            <div class="col-sm-4">
                                <a href="javascript:void(0)" class="btn btn-sm btn-default pull-left">Añadir</a>
                            </div>
                            <div class="col-sm-12" style="margin: 20px;">
                                <div class="personas-box">
                                    <table>
                                        <tbody>
                                        <tr>
                                            <td class="to-left"><i class="gi gi-user" style="margin-right: 40px: "></i> Jara, Miguel</td>
                                            <td><a href="javascript:void(0)">
                                                    <i class="gi gi-remove_2" style="color:gray;"></i>
                                                </a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="to-left"><i class="gi gi-user" style="margin-right: 40px: "></i> Rodriguez, Puma</td>
                                            <td><a href="javascript:void(0)">
                                                    <i class="gi gi-remove_2" style="color:gray;"></i>
                                                </a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="to-left"><i class="gi gi-user" style="margin-right: 40px: "></i> Salas, Marcelo</td>
                                            <td><a href="javascript:void(0)">
                                                    <i class="gi gi-remove_2" style="color:gray;"></i>
                                                </a>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>

                                </div>
                                <div class="sugerencias-box">
                                    <a id="openSugerencias" href="javascript:void(0)" class="pull-left">Sugerencias de Horas</a>
                                </div>
                                <div class="bubble-msg">
                                    <div class="item-horario">
                                        <strong>viernes 10/06 12.00</strong>
                                        <p>Todos pueden</p>
                                    </div>
                                    <div class="item-horario">
                                        <strong>viernes 10/06 14.00</strong>
                                        <p>Todos pueden</p>
                                    </div>
                                    <div class="item-horario">
                                        <strong>viernes 10/06 15.00</strong>
                                        <p>Todos pueden</p>
                                    </div>
                                    <div class="item-horario">
                                        <strong>viernes 10/06 16.00</strong>
                                        <p>Todos pueden</p>
                                    </div>
                                    <div class="item-horario">
                                        <strong>viernes 10/06 17.00</strong>
                                        <p>Todos pueden</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>