<div class="base-page lighter">

    <aside>
        <h1 class="blog">Creación Evento</h1>
    </aside>

    <div>
        <a href="javascript:void(0)"  onclick="$('#evento-form').submit();" class="btn btn-success pull-right btn-save">Guardar</a>
    </div>
    <div class="formulario-section">
        <form id='frm' action="<?php print($this->url->get("actividad")) ?>"></form>
        
        <form id="evento-form" action="<?php print($this->url->get("actividad/guardarEvento")) ?>" method="post" data-type="ajax">
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-content">

                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="dscr-breve">Proyecto *</label>
                            <div class="col-sm-8">
                                <select id="proyecto" name="proyecto" class="form-control input-sm">
                                    <option value="0">Seleccione</option>
                                    <?php
                                        foreach ($pcData['proyectos'] as $proyecto) {
                                            echo "<option value='".$proyecto->id."'>".$proyecto->nombre."</option>";
                                        }

                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="dscr-breve">Descripción Breve *</label>
                            <div class="col-sm-8">
                                <input type="text" id="dscr-breve" name="dscr-breve" class="form-control input-sm" placeholder="Descripción Breve">
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="dscr-ampliada">Descripción Ampliada *</label>
                            <div class="col-sm-8">
                                <textarea id="dscr-ampliada" name="dscr-ampliada" rows="5" class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="donde">¿Dónde? *</label>
                            <div class="col-sm-8">
                                <input type="text" id="donde" name="donde" class="form-control input-sm" placeholder="Lugar">
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="categoria">Categoría *</label>
                            <div class="col-sm-8" style="text-align: left;">
                                <select id="categoria" name="categoria" class="select-chosen my-chosen" data-placeholder="Seleccionar..." style="width: 250px;">
                                    <option value="" selected=""></option>
                                    <?php foreach($pcData['categoria'] as $categoriaItem ) {?>
                                        <option value="<?php print $categoriaItem->ctgr_id ?>"><?php print $categoriaItem->ctgr_nombre ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row form-row my-chosen">
                            <label class="col-sm-4 control-label" for="persona">Añadir Persona *</label>

                            <div class="col-sm-8" style="text-align: left;">
                                <select id="persona" name="persona" class="select-chosen" data-placeholder="Seleccionar..." style="width: 250px;">
                                        <option></option>
                                </select>
                            </div>
                        </div>                        
                    </div>

                </div>
                <div class="col-sm-3 col-sm-offset-1">
                    <div class="form-content">
                        <div class="form-group row">
                            <div id="datepicker" data-date-format="yyyy-mm-dd" data-date="<?php print(isset($pcData['fechaSelected'])?$pcData['fechaSelected']:date('Y-m-d')) ?>"></div>
                            <input type="hidden" id="fecha" name="fecha" value="<?php print(isset($pcData['fechaSelected'])?$pcData['fechaSelected']:date('Y-m-d')) ?>">
                        </div>
                        <div class="form-group row form-row">
                            <div class="input-group bootstrap-timepicker" style="padding-left: 0px;">
                                <input style="margin-left:15px;" type="text" id="hora" name="hora" class="form-control input-timepicker24" value="<?php print(isset($pcData['horaSelected'])?$pcData['horaSelected']:"13:00") ?>">
                                <span class="input-group-btn">
                                    <a href="javascript:void(0)" class="btn btn-primary"><i class="fa fa-clock-o"></i></a>
                                </span>
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-12 control-label" for="duracion">Duración (Horas) *</label>
                            <div class="col-sm-12">
                                <input type="time" id="duracion" name="duracion" class="form-control input-sm" value="1" placeholder="Duración" readonly>
                            </div>
                        </div>
                        <div class="form-group row" style="text-align: center;">
                            <?php
                                if(isset($pcData['userSelected']->id)) {
                                    $userBloque = $pcData['userSelected']->id;
                                }else {
                                    $userBloque = '';
                                }
                            ?>
                            <a id="btnBloqueLibre" href="<?php print($this->url->get("gestionQa/encontrarBloque")) ?>" data-action="<?php print($this->url->get("gestionQa/encontrarBloque")) ?>" data-val="fecha=<?php print(isset($pcData['fechaSelected'])?$pcData['fechaSelected']:date('Y-m-d')) ?>&persona=<?php print $userBloque ?>">Encontrar Bloque Libre</a>
                        </div>                        
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div id="modal-bloqueLibre" class="modal fade"></div>