<div class="modal-dialog" style="width: 40%;">
    <div class="modal-content">
        <div class="modal-body item" style="min-height:60vh;">
            <div class="modal-msg-box">
                <div class="header-item">
                    <strong>Evento: <?php print($pcData['actividad']->actv_descripcion_breve); ?></strong>
                </div>
                <div class="subheader-item">
                    <div class="row">
                        <div class="col-xs-12 title-table">Cuándo</div>
                        <div class="col-xs-12"><?php print($pcData['actividad']->actv_fecha); ?>, <?php print(date('H:i',strtotime($pcData['actividad']->actv_hora))." - ".date('H:i',strtotime($pcData['actividad']->actv_hora." + 1 hours"))); ?></div>
                    </div>
                </div>
                <div class="data-item">
                    <table>
                        <tbody>
                           <tr>
                               <td class="title-table">Descripción</td>
                               <td><?php print($pcData['actividad']->actv_descripcion_ampliada); ?></td>
                           </tr>
                           <tr>
                               <td class="title-table">Estado</td>
                               <td><?php print($pcData['actividad']->actv_status); ?></td>
                           </tr>
                           <tr>
                               <td class="title-table">Lugar</td>
                               <td><?php print($pcData['actividad']->actv_location); ?></td>
                           </tr>
                           <tr>
                               <td class="title-table">Duración</td>
                               <td>1 hr</td>
                           </tr>
                           <tr>
                               <td class="title-table">Prioridad</td>
                               <td><?php print($pcData['actividad']->Prioridad->prrd_nombre); ?></td>
                           </tr>
                           <tr>
                               <td class="title-table">Acceso</td>
                               <td><?php print($pcData['actividad']->Acceso->accs_nombre); ?></td>
                           </tr>
                           <tr>
                               <td class="title-table">Categoría</td>
                               <td>
                                   <span class="label label-custom">
                                       Instalación
                                   </span>
                               </td>
                           </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="links-box">
                <a class="dismiss-item link-modal" href="javascript:void(0)" data-dismiss="modal">Editar</a>
                <a class="dismiss-item link-modal" href="javascript:void(0)" data-dismiss="modal">Cerrar</a>
            </div>
        </div>
    </div>
</div>