<div class="modal-dialog" style="width: 70%;">
    <div class="modal-content">
        <div class="modal-body item" style="min-height:80vh;>
            <div class="modal-msg-box">
                <div class="header-item">
                    <strong><i class="fa fa-shield"></i> Evento # 65556: Revisión de Código</strong>
                </div>
                <div class="subheader-item">
                    <div class="row">
                        <div class="col-xs-12 title-table">Cuándo</div>
                        <div class="col-xs-12">lun, 6 de junio, 8:00am – 9:00am</div>
                    </div>
                </div>
                <div class="data-item">
                    <table>
                        <tbody>
                           <tr>
                               <td class="title-table">Descripción</td>
                               <td>Revisar módulo de carga de archivos</td>
                           </tr>
                           <tr>
                               <td class="title-table">Estado</td>
                               <td>Esperando Revisión</td>
                           </tr>
                           <tr>
                               <td class="title-table">Lugar</td>
                               <td>Dependencias del cliente: Softland</td>
                           </tr>
                           <tr>
                               <td class="title-table">Duración</td>
                               <td>1 hr</td>
                           </tr>
                           <tr>
                               <td class="title-table">Prioridad</td>
                               <td><span class="label label-danger">5-medio</span</td>
                           </tr>
                           <tr>
                               <td class="title-table">Acceso</td>
                               <td>Público</td>
                           </tr>
                           <tr>
                               <td class="title-table">Categoría</td>
                               <td>
                                   <span class="label label-custom">Instalación</span>
                                   <span class="label label-custom">Proyecto IMSA</span>
                               </td>
                           </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <a class="pull-right dismiss-item" href="javascript:void(0)" data-dismiss="modal">Cerrar</a>
        </div>
    </div>
</div>