<div class="base-page lighter">
    <div class="row header-color">
        <div class="col-md-12 col-lg-12">
            <div class="header-container">
                <div class="header-perfil">
                    <i class="gi gi-bookmark"></i>

                    <?php

                    print($pcData['actividades']->actv_descripcion_breve);

                    ?>

                </div>

                <div class="header-bajada">

                    <?php

                        print($pcData['actividades']->actv_fecha);
                    ?>,
                    <?php

                        print(date('H:i',strtotime($pcData['actividades']->actv_hora)).
                            " - ".
                            date('H:i',strtotime($pcData['actividades']->actv_hora." + 1 hours")));
                    ?>

                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            <!-- Course Widget -->
            <div class="widget">
                <div class="widget-advanced">
                    <!-- Widget Header -->
                    <!-- END Widget Header -->

                    <!-- Widget Main -->
                    <div class="widget-main" style="padding-top: 35px; background-color: white;">
                        <ul class="nav nav-tabs push" data-toggle="tabs">
                            <li class="active">
                                <a href="#actTab">Actividades</a>
                            </li>
                            <li>
                                <a href="#docTab">Documentos</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="actTab" style="position: relative;">
                                <div class="widget-options" style="top: -10px;z-index: 1;">
                                    <button href="#modal-new-actividad" data-toggle="modal" class="enable-tooltip btn btn-xs btn-success" title="Nueva Actividad"><i class="fa fa-plus"></i></button>
                                </div>
                                <!-- Timeline Content -->
                                <div id="timeline" class="timeline">

                                    <?php echo $this->view->render('actividad/actividad_hitos_view',array('pcData'=>$pcData))?>


                                </div>
                                <!-- END Timeline Content -->

                            </div>
                            <div class="tab-pane" id="docTab" style="position: relative;">
                                <div class="widget-options" style="top: -10px;z-index: 1;">
                                    <a href="#modal-cargar" data-toggle="modal"class="enable-tooltip btn btn-xs btn-success" title="Cargar Documento">
                                        <i class="gi gi-cloud_plus"></i>
                                    </a>
                                </div>

                                <table class="table table-vcenter table-striped">
                                    <thead>
                                        <tr>
                                            <th class="text-center"><i class="fa fa-folder-open-o"></i></th>
                                            <th>Nombre</th>
                                            <th class="hidden-xs">Fecha</th>
                                            <th class="hidden-sm hidden-xs">Usuario</th>
                                            <th class="text-center">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody id="archivos_tr">
                                        <?php echo $this->view->render('actividad/archivos_tr', array('pcData'=>$pcData));?>
                                    </tbody>
                                </table>


                            </div>
                        </div>

                    </div>
                    <!-- END Widget Main -->
                </div>
            </div>
            <!-- END Course Widget -->
        </div>
        <div class="col-md-4">

            <!-- Most Viewed Courses Block -->
            <div class="my-block">
                <div class="item">
                    <div class="title">
                        Datos Relevantes
                        <a href="<?php print $this->url->get("actividad/editar/".$pcData['actividades']->actv_id) ?>" class="link-modal pull-right" style="font-size: 15px;"><i class="fa fa-cog"></i> Editar</a>
                    </div>
                    <hr>
                    <p class="descrp-evento">
                        <?php print($pcData['actividades']->actv_descripcion_ampliada); ?>
                    </p>
                    <table>
                        <tbody>
                        <tr>
                            <td class="title-table">Estado</td>
                            <td class="title-table"><?php print($pcData['actividades']->actv_status); ?></td>
                        </tr>
                        <tr>
                            <td class="title-table">Lugar</td>
                            <td class="title-table"><?php print($pcData['actividades']->actv_location); ?></td>
                        </tr>
                        <tr>
                            <td class="title-table">Duración</td>
                            <td class="title-table">1 hr</td>
                        </tr>
                        <tr>
                            <td class="title-table">Prioridad</td>
                            <td class="title-table"><?php print($pcData['actividades']->Prioridad->prrd_nombre); ?></td>
                        </tr>
                        <tr>
                            <td class="title-table">Acceso</td>
                            <td class="title-table"><?php print($pcData['actividades']->Acceso->accs_nombre); ?></td>
                        </tr>
                        <tr>
                            <td class="title-table">Categoría</td>
                            <td class="title-table">
                                   <span class="label label-custom">
                                       <?php foreach($pcData['actividades']->CategoriaActividad as $iter ) {
                                           print($iter->Categoria->ctgr_nombre." ");
                                       } ?>
                                   </span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>

                <div class="item">
                    <div class="title">
                        Participantes
                    </div>
                    <hr>
                    <ul class="user-list">

                        <li>
                            <div class="row">
                                <div class="col-xs-4 user">
                                    <div class="avatar-circle">
                                        <?php

                                            $user_owner = $pcData['actividades']->actv_creado_por;
                                            $iniciales = explode(" ", $user_owner);
                                            $frst = isset($iniciales[0])?str_split($iniciales[0])[0]:'';
                                            $scnd =  isset($iniciales[1])?str_split($iniciales[1])[0]:'';


                                        ?>
                                        <span class="initials"><?php print $frst.$scnd ?></span>
                                    </div>

                                            <?php
                                                if(isset($iniciales[0]) && isset($iniciales[1])) {
                                                    print($iniciales[0] . " " . $iniciales[1]);
                                                }
                                                else {
                                                    print $iniciales[0];
                                                }
                                            ?>

                                    <br>
                                    Creador Evento
                                </div>

                                

                                <?php

                                    foreach($pcData['actividades']->UserActividad as $iter ) { ?>
                                        <div class="col-xs-4 user">

                                            <?php

                                                if(isset($iter->Users->avatar)) {

                                            ?>
                                                    <a href="javascript:void(0)" id="chat-user1" class="chat-user-online themed-color-night" style="text-decoration:none;">
                                                        <img src="<?php print($this->url->get($iter->Users->avatar))?>" alt="avatar" class="img-circle" width="64" height="64">
                                                    </a>
                                                    <br>
                                                    <?php print $iter->Users->name ?> <br>
                                                    <?php print $iter->Users->rol->descripcion ?>
                                            <?php

                                                } else {

                                                    $iniciales = explode(" ", $iter->Users->name);
                                                    $frst = str_split($iniciales[0])[0];
                                                    $scnd = str_split($iniciales[1])[0];
                                            ?>

                                                <div class="avatar-circle">
                                                    <span class="initials"><?php print $frst.$scnd ?></span>
                                                </div>
                                                <?php print $iter->Users->name ?> <br>
                                                <?php print $iter->Users->rol->descripcion ?>

                                            <?php

                                                }
                                            ?>

                                        </div>
                                <?php
                                    }
                                ?>

                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- END Most Viewed Courses Block -->

        </div>
    </div>

</div>


<div id="modal-cargar" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header text-center">
                <h2 class="modal-title"><i class="fa fa-plus"></i> CARGAR</h2>
            </div>
            <!-- END Modal Header -->

            <!-- Modal Body -->
            <div class="modal-body">                    
                <form action="<?php print($this->url->get("actividad/uploadArchivo")) ?>" class="dropzone" id="dropId">
                    <div id="dropzonePreview" class="dz-default dz-message">
                    <span>Haga Click o <br/>Arrastre los Archivos para ser cargados</span>
                    </div>
                    <input type="hidden" name="actividad" value="<?php print($pcData['actividades']->actv_id)?>">
                </form>
            </div>
            <!-- END Modal Body -->
        </div>
    </div>
</div>
                    
<div id="modal-new-actividad" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header text-center">
                <h2 class="modal-title"><i class="fa fa-plus"></i> Nueva Actividad</h2>
            </div>
            <!-- END Modal Header -->

            <!-- Modal Body -->
            <div class="modal-body">
                <form action="<?php print($this->url->get("hito/crearHito")) ?>" id="modal-new-actividad-form" method="POST" class="form-horizontal form-bordered" data-type="ajax">
                    <input type="hidden" name="idActividad" value="<?php print($pcData['actividades']->actv_id)?>">
                    <div class="form-content">
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="hitoTipo">Tipo *</label>
                            <div class="col-sm-8">
                                <select id="hitoTipo" name="hitoTipo" class="form-control" data-placeholder="Ingrese o Seleccione un Tipo" style="width: 250px;">
                                    <option value="fa fa-cogs">Procedimiento</option>
                                    <option value="fa fa-file-text">Nota Libre</option>
                                    <option value="fa fa-pencil">Gestión</option>
                                    <option value="fa fa-users">Reunión</option>
                                    <option value="fa fa-2x fa-mobile">Comunicación</option>
                                    <option value="fa fa-commenting-o">Comentario</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="hitoNombre">Nombre *</label>
                            <div class="col-sm-8">
                                <input type="text" id="hitoNombre" name="hitoNombre" class="form-control input-sm" placeholder="Nombre">
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="hitoDescripcion">Descripción *</label>
                            <div class="col-sm-8">
                                <textarea id="hitoDescripcion" name="hitoDescripcion" rows="5" class="form-control"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row form-actions">
                        <div class="col-xs-12 text-right">
                            <button id="modal-new-actividad-dismiss" type="button" class="btn btn-sm btn-default" data-dismiss="modal">Cerrar</button>
                            <button id="modal-new-actividad-submit" type="submit" class="btn btn-sm btn-primary">Crear</button>
                        </div>
                    </div>
                </form>
            </div>
            <!-- END Modal Body -->
        </div>
    </div>
</div>
