<?php
    $hitos = $pcData['actividades']->getHito(array("order"=>"created_at DESC"));

    if(isset($hitos) && count($hitos) >0 ) {
    ?>

    <ul class="timeline-list" id="actList">

        <?php

        foreach ($hitos as $iter) {
            ?>
            <li class="active">
                <div class="timeline-icon"><i class="<?php print $iter->hito_tipo ?>"></i></div>
                <div class="timeline-time">
                    <small>
                        <?php print date("d ", strtotime($iter->created_at)) ?>
                        <?php print($this->config['dateES']['meses_mini'][(int)date("m", strtotime($iter->created_at))-1].", ") ?>
                        <?php print date("Y H:i", strtotime($iter->created_at)) ?>
                    </small>
                </div>
                <div class="timeline-content">
                    <p class="push-bit">
                        <a href="javascript:void(0)">
                            <strong><?php print $iter->hito_nombre ?></strong>
                        </a>
                    </p>
                    <?php print $iter->hito_descripcion ?>
                </div>
            </li>


            <?php

        }
        ?>

    </ul>

    <?php
} else { ?>
    <div style="padding: 20px;">
        <h4> Aún no se han creado hitos para este evento, presiona sobre el botón
            <button href="#modal-new-actividad" data-toggle="modal" class="enable-tooltip btn btn-xs btn-success" title="Nueva Actividad">
                <i class="fa fa-plus"></i>
            </button>
            para crear uno.
        </h4>
    </div>

    <?php

}

?>