<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">

			<div class="panel panel-default">
  				<div class="panel-body">

					<form action="<?php echo $this->url->get('actividad/buscar'); ?>" method='GET'>
						
						<div class="col-md-12">
							<div class="form-group">
								<label for="search">Buscar</label>
								<input type="text" name='search' class="form-control" value="<?php echo (isset($_GET['search']))?$_GET['search']:'' ?>">
							</div>
						</div>
						
						<div class="col-md-9">
							<div class="form-group">
								<label for="user">Coordinador</label>
								<select name='user' class="form-control select-chosen">
									<option value="">Seleccione</option>
									<?php
										$users = $pcData['users'];

										$usr_slc = $_GET['user'];

										foreach ($users as $user) {
											
											if(!empty($usr_slc) and $usr_slc == $user->id){
												$selected = 'selected';
											}else{
												$selected = '';
											}

											echo "<option value='".$user->id."' $selected>".$user->name."</option>";
										}
									?>
								</select>
							</div>
						</div>
							
						<div class="col-md-3">
							<div class="form-group">
								<label for="">&nbsp;</label>
								<button type='submit' class='btn btn-default form-control'>Buscar</button>
							</div>
						</div>

					
				</div>
			</div>
		</div>
	</div>
		


	<div class="row">
		<?php

			if(isset($pcData['page'])){
				# Mostrando resultados
				echo "<h1>buscando: ".$pcData['search']."</h1>";
				echo "<ul>";
				foreach ($pcData['page']->items as $actividad)
				{
					echo "<li>".$actividad->actv_descripcion_breve."</li>";
				}
				echo "</ul>";


				# armo la url
				$url = '';

				if(isset($_GET['search'])){
					$url .= "&search=".$_GET['search'];
				}else{
					$url .= "search=";
				}
				
				if(isset($_GET['user'])){
					$url .= "&user=".$_GET['user'];
				}else{
					$url .= "user=";
				}


				# solo mostramos la paginación si el numero de paginas es mayor a 1
				if( $pcData['page']->total_pages > 1){

				
				?>



				<nav>
					<ul class="pagination">

						<li><a href="/qalendar/actividad/buscar">First</a></li>

						<li>
							<a href="/qalendar/actividad/buscar?<?=$url?>&page=<?= $pcData['page']->before; ?>" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
							</a>
						</li>					
						
						<li>
							<a href="/qalendar/actividad/buscar?<?=$url?>&page=<?= $pcData['page']->next; ?>" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
							</a>
						</li>

						<li><a href="/qalendar/actividad/buscar?<?=$url?>&page=<?= $pcData['page']->last; ?>">Last</a></li>
					</ul>
				</nav>




				<a href="/qalendar/actividad/buscar">First</a>
				<a href="/qalendar/actividad/buscar?<?=$url?>&page=<?= $pcData['page']->before; ?>">Previous</a>
				<a href="/qalendar/actividad/buscar?<?=$url?>&page=<?= $pcData['page']->next; ?>">Next</a>
				<a href="/qalendar/actividad/buscar?<?=$url?>&page=<?= $pcData['page']->last; ?>">Last</a>
				
				</form>
		<?php 

					echo "Estas en la página ", $pcData['page']->current, " de ", $pcData['page']->total_pages; 

				}// endif	

			}
		?>


	</div>
</div>
	

	