<div class="base-page lighter">
        <div class="col-md-10 col-md-offset-1">
            <h2>Edición de evento</h2>
        </div>

    <div >

        <?php

            if($this->AccesoAcl->tienePermiso('guardarevento', 'actividad')) { ?>
                
                <a  href="javascript:void(0)"  
                    onclick="$('#evento-form').submit();" 
                    class="btn btn-success pull-right btn-save">Guardar</a>

        <?php 
            } 
        ?>

        <?php
/*
            if($this->AccesoAcl->tienePermiso('crearhito')) { ?>
                
                <a  href="#"  
                    class="btn btn-success pull-right btn-save" 
                    data-toggle="modal" 
                    data-target="#modal_hito">Hito</a>

        <?php 
            } */
        ?>
        

        
    </div>
    <div class="formulario-section">
        <form id='frm' action="<?php print($this->url->get("actividad")) ?>"></form>

        <form id="evento-form" action="<?php print($this->url->get("actividad/editarEvento")) ?>" method="post" data-type="ajax">
            <input type='hidden' name='id' id='id' value='<?php echo $pcData['actividad']->actv_id; ?>' />
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-content">


                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="dscr-breve">Proyecto *</label>
                            <div class="col-sm-8">
                                <select id="proyecto" name="proyecto" class="form-control input-sm">
                                    <option value="0">Seleccione</option>
                                    <?php
                                        foreach ($pcData['proyectos'] as $proyecto) {

                                            if($pcData['actividad']->proyecto_id == $proyecto->id){
                                                $selected = 'selected';
                                            }else{
                                                $selected = '';
                                            }

                                            echo "<option value='".$proyecto->id."' $selected>".$proyecto->nombre."</option>";
                                        }

                                    ?>
                                </select>
                            </div>
                        </div>


                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="dscr-breve">Descripción Breve *</label>
                            <div class="col-sm-8">
                                <input type="text" id="dscr-breve" name="dscr-breve" class="form-control input-sm" placeholder="Descripción Breve" value="<?php echo $pcData['actividad']->actv_descripcion_breve;?>">
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="dscr-ampliada">Descripción Ampliada *</label>
                            <div class="col-sm-8">
                                <textarea id="dscr-ampliada" name="dscr-ampliada" rows="5" class="form-control"><?php echo $pcData['actividad']->actv_descripcion_ampliada?></textarea>
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="donde">¿Dónde? *</label>
                            <div class="col-sm-8">
                                <input type="text" id="donde" name="donde" class="form-control input-sm" placeholder="Descripción Breve" value="<?php echo $pcData['actividad']->actv_location;?>">
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="categoria">Categoría *</label>
                            <div class="col-sm-8" style="text-align: left;">

                                <select id="categoria" name="categoria" class="select-chosen my-chosen" data-placeholder="Elegir Categorías" style="width: 250px;">
                                    <option value="" selected=""></option>
                                    <?php 

                                        foreach($pcData['categorias'] as $categoriaItem ) {

                                            if(in_array($categoriaItem->ctgr_id, $pcData['catAct']))
                                            {
                                                $selected = "selected";
                                            }else{
                                                $selected = "";
                                            }

                                        ?>
                                            <option value="<?php print $categoriaItem->ctgr_id ?>" <?php echo $selected; ?> ><?php print $categoriaItem->ctgr_nombre ?></option>
                                        <?php } ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group row form-row my-chosen">
                            <label class="col-sm-4 control-label" for="persona">Añadir Persona *</label>

                            <div class="col-sm-8" style="text-align: left;">

                                <input id='qa_selected' name='qa_selected' value='<?php echo $pcData['usersSelected']; ?>' type='hidden'>

                                <select id="persona" name="persona" class="select-chosen" data-placeholder="Seleccionar..." value="1" style="width: 250px;">
                                </select>
                            </div>
                        </div>                        
                    </div>
                </div>
                <div class="col-sm-3 col-md-offset-1">
                    <div class="form-group row form-row">
                        <div id="datepicker" data-date-format="yyyy-mm-dd" data-date="<?php print(isset($pcData['fechaSelected'])?$pcData['fechaSelected']:date('Y-m-d')) ?>"></div>
                        <input type="hidden" id="fecha" name="fecha" value="<?php print(isset($pcData['fechaSelected'])?$pcData['fechaSelected']:date('Y-m-d')) ?>">
                    </div>
                    <div class="form-group row form-row">
                        <div class="input-group bootstrap-timepicker" style="padding-left: 0px;">
                            <input style="margin-left:15px;" type="text" id="hora" name="hora" class="form-control input-timepicker24" value="<?php print(isset($pcData['horaSelected'])?$pcData['horaSelected']:"13:00") ?>" disabled>
                            <span class="input-group-btn">
                                <a href="javascript:void(0)" class="btn btn-primary"><i class="fa fa-clock-o"></i></a>
                            </span>
                        </div>
                    </div>
                    <div class="form-group row form-row">
                        <label class="col-sm-12 control-label" for="duracion">Duración (Horas) *</label>
                        <div class="col-sm-12">
                            <input type="time" id="duracion" name="duracion" class="form-control input-sm" value="<?php echo $pcData['duracion'];?>" placeholder="Duración" readonly>
                        </div>
                    </div>
                    <div class="form-group row" style="text-align: center;">
                        <a id="btnBloqueLibre" href="<?php print($this->url->get("gestionQa/encontrarBloque")) ?>"
                           data-action="<?php print($this->url->get("gestionQa/encontrarBloque")) ?>"
                           data-val="fecha=<?php print(date('Y-m-d')) ?>&persona=<?php print($pcData['usersSelected']) ?>"
                           class="">Encontrar Bloque Libre</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div id="modal-bloqueLibre" class="modal fade"></div>

<input type='hidden' id='idactividad' name='idactividad' value='<?php echo $pcData['actividad']->actv_id; ?>' />

<div class="modal fade" tabindex="-1" role="dialog" id='modal_hito'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Agregar Hitos</h4>
            </div>

            <form class='form-inline' action="<?php print $this->url->get('hito')?>" id='frm'></form>

            <div class="modal-body">
                <div class="row">
                    <button class='btn btn-success pull-right add-actividad'>+</button>
                    <p>lista de hitos</p>  
                </div>


                <div id="message_error"></div>

                <div class="row" id='hitos'>

                </div>
                
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary">Guardar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->