<div class="base-page lighter">

    <hr><hr>
    <div >
        <a href="javascript:void(0)"  onclick="$('#evento-form').submit();" class="btn btn-success pull-right btn-save">Guardar</a>
    </div>
    <div class="formulario-section">
        <form id="evento-form" action="<?php print($this->url->get("actividad/editarEvento")) ?>" method="post" data-type="ajax">
            <div class="row">
                <div class="col-sm-5">
                    <div class="form-content">
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="dscr-breve">Descripción Breve *</label>
                            <div class="col-sm-8">
                                <input type="text" id="dscr-breve" name="dscr-breve" class="form-control input-sm" placeholder="Descripción Breve" value="<?php echo $pcData['actividad']->actv_descripcion_breve;?>">
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="dscr-ampliada">Descripción Ampliada *</label>
                            <div class="col-sm-8">
                                <textarea id="dscr-ampliada" name="dscr-ampliada" rows="5" class="form-control"><?php echo $pcData['actividad']->actv_descripcion_ampliada?></textarea>
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="donde">¿Dónde? *</label>
                            <div class="col-sm-8">
                                <input type="text" id="donde" name="donde" class="form-control input-sm" placeholder="Descripción Breve" value="<?php echo $pcData['actividad']->actv_location;?>">
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="categoria">Categoría *</label>
                            <div class="col-sm-8">

                                <select id="categoria" name="categoria" class="select-chosen my-chosen" data-placeholder="Elegir Categorías" style="width: 250px;">
                                    <option value="" selected=""></option>
                                    <?php 

                                        foreach($pcData['categorias'] as $categoriaItem ) {

                                            if(in_array($categoriaItem->ctgr_id, $pcData['catAct']))
                                            {
                                                $selected = "selected";
                                            }else{
                                                $selected = "";
                                            }

                                        ?>
                                            <option value="<?php print $categoriaItem->ctgr_id ?>" <?php echo $selected; ?> ><?php print $categoriaItem->ctgr_nombre ?></option>
                                        <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row form-row">
                            <label class="col-sm-4 control-label" for="acceso">Acceso *</label>
                            <div class="col-sm-8" style="text-align: left;">
                                <select id="acceso" name="acceso" class="select-chosen my-chosen" data-placeholder="Seleccionar..." style="width: 250px;">
                                    <option value=""></option>
                                    <?php foreach($pcData['accesos'] as $accesoItem ) {

                                            if($pcData['actividad']->accs_id == $accesoItem->accs_id)
                                            {
                                                $selected = "selected";
                                            }else{
                                                $selected = "";
                                            }

                                        ?>
                                        <option value="<?php print $accesoItem->accs_id ?>" <?php echo $selected; ?> ><?php print $accesoItem->accs_nombre ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row form-row my-chosen">
                            <label class="col-sm-4 control-label" for="prioridad">Prioridad *</label>
                            <div class="col-sm-8" style="text-align: left;">
                                <select id="prioridad" name="prioridad" class="select-chosen" data-placeholder="Seleccionar..." style="width: 250px;">
                                    <option></option>
                                    <?php foreach($pcData['prioridades'] as $prioridadItem ) {


                                            if($pcData['actividad']->prrd_id == $prioridadItem->prrd_id)
                                            {
                                                $selected = "selected";
                                            }else{
                                                $selected = "";
                                            }
                                        ?>
                                        <option value="<?php print $prioridadItem->prrd_id ?>" <?php echo $selected; ?> ><?php print $prioridadItem->prrd_nombre ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group row form-row">
                        <div id="datepicker" data-date-format="yyyy-mm-dd" data-date="<?php print(isset($pcData['fechaSelected'])?$pcData['fechaSelected']:date('Y-m-d')) ?>"></div>
                        <input type="hidden" id="fecha" name="fecha" value="<?php print(isset($pcData['fechaSelected'])?$pcData['fechaSelected']:date('Y-m-d')) ?>">
                    </div>
                    <div class="form-group row form-row">
                        <div class="input-group bootstrap-timepicker" style="padding-left: 0px;">
                            <input style="margin-left:15px;" type="text" id="hora" name="hora" class="form-control input-timepicker24" value="<?php print(isset($pcData['horaSelected'])?$pcData['horaSelected']:"13:00") ?>">
                            <span class="input-group-btn">
                                <a href="javascript:void(0)" class="btn btn-primary"><i class="fa fa-clock-o"></i></a>
                            </span>
                        </div>
                    </div>
                    <div class="form-group row form-row">
                        <label class="col-sm-12 control-label" for="duracion">Duración (Horas) *</label>
                        <div class="col-sm-12">
                            <input type="Number" id="duracion" name="duracion" class="form-control input-sm" value="<?php echo $pcData['actividad']->actv_duracion_horas;?>" placeholder="Duración">
                        </div>
                    </div>
                    <div class="form-group row" style="text-align: center;">
                        <a id="btnBloqueLibre" href="<?php print($this->url->get("gestionQa/encontrarBloque")) ?>" data-action="<?php print($this->url->get("gestionQa/encontrarBloque")) ?>" data-val="fecha=<?php print(date('Y-m-d')) ?>" class="">Encontrar Bloque Libre</a>
                    </div>
                </div>
                <div class="col-sm-5">
                    <div class="form-content">
                        <div class="form-group row form-row my-chosen">
                            <label class="col-sm-12 control-label" for="persona">Añadir Persona *</label>

                            <div class="col-sm-8" style="text-align: left;">
                                <select id="persona" name="persona" class="select-chosen" data-placeholder="Seleccionar..." value="1" style="width: 250px;">
                                        <option></option>
                                    <?php foreach($pcData['users'] as $persona ) {


                                        if($pcData['usersSelected'] == $persona->id)
                                        {
                                            $selected = 'selected';
                                        }else{
                                            $selected = '';
                                        }

                                        ?>
                                        <option value="<?php print $persona->id; ?>" <?php echo $selected;?> ><?php print $persona->name; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <!--
                            <div class="col-sm-4">
                                <a href="javascript:void(0)" class="btn btn-sm btn-default pull-left">Añadir</a>
                            </div>
                            <div class="col-sm-12" style="margin: 20px;">
                                <div class="personas-box">
                                    <table>
                                        <tbody>
                                        <tr>
                                            <td class="to-left"><i class="gi gi-user" style="margin-right: 40px: "></i> Jara, Miguel</td>
                                            <td><a href="javascript:void(0)">
                                                    <i class="gi gi-remove_2" style="color:gray;"></i>
                                                </a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="to-left"><i class="gi gi-user" style="margin-right: 40px: "></i> Rodriguez, Puma</td>
                                            <td><a href="javascript:void(0)">
                                                    <i class="gi gi-remove_2" style="color:gray;"></i>
                                                </a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="to-left"><i class="gi gi-user" style="margin-right: 40px: "></i> Salas, Marcelo</td>
                                            <td><a href="javascript:void(0)">
                                                    <i class="gi gi-remove_2" style="color:gray;"></i>
                                                </a>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>

                                </div>
                                <div class="sugerencias-box">
                                    <a id="openSugerencias" href="javascript:void(0)" class="pull-left">Sugerencias de Horas</a>
                                </div>
                                <div class="bubble-msg">
                                    <div class="item-horario">
                                        <strong>viernes 10/06 12.00</strong>
                                        <p>Todos pueden</p>
                                    </div>
                                    <div class="item-horario">
                                        <strong>viernes 10/06 14.00</strong>
                                        <p>Todos pueden</p>
                                    </div>
                                    <div class="item-horario">
                                        <strong>viernes 10/06 15.00</strong>
                                        <p>Todos pueden</p>
                                    </div>
                                    <div class="item-horario">
                                        <strong>viernes 10/06 16.00</strong>
                                        <p>Todos pueden</p>
                                    </div>
                                    <div class="item-horario">
                                        <strong>viernes 10/06 17.00</strong>
                                        <p>Todos pueden</p>
                                    </div>
                                </div>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div id="modal-bloqueLibre" class="modal fade"></div>