<?php
    if(isset($actividades) && count($actividades) >0 ) {
?>

    <ul class="timeline-list" id="actList">

        <?php

        foreach ($actividades as $act) {
            ?>
            <li class="active">
                <div class="timeline-icon"><span class="icon-timeline icon-timeline-<?php echo $act->actv_categoria;?>"></span></div>
                <div class="timeline-time">
                    <small>
                        <?php print date("d ", strtotime($act->actv_created_at)) ?>
                        <?php print($this->config['dateES']['meses_mini'][(int)date("m", strtotime($act->actv_created_at))-1].", ") ?>
                        <?php print date("Y ", strtotime($act->actv_created_at)) ?>
                    </small>
                </div>
                <div class="timeline-content">
                    <p class="push-bit">
                        <a href="
                            <?php
                                if($this->AccesoAcl->tienePermiso('verperfilevento', 'actividad'))
                                { 
                                    echo $this->url->get('actividad/perfil/').$act->actv_id;
                                }
                            ?>" target='_blank'>
                            <strong><?php print $act->actv_descripcion_breve ?></strong>
                        </a>
                    </p>
                    <?php print $act->actv_descripcion_ampliada ?>
                </div>
            </li>


            <?php

        }
        ?>

    </ul>

    <?php
} else { ?>
    <div style="padding: 20px;">
        <h4> Aún no se han creados eventos asociados a este proyecto.
        </h4>
    </div>

    <?php

}

?>