<html>
<head>
	<meta charset="UTF-8">
	<title>{{ titulo }}</title>
</head>
<body>
	<p>Estimad@, {{ mensaje }}</p>

	<p>Detalles del evento:

	<table>
		<tr><td>Nombre:</td><td>{{ nombre }}</td></tr>
		<tr><td>Lugar:</td><td>{{ lugar }}</td></tr>
		<tr><td>Fecha:</td><td>{{ fecha }}</td></tr>
		<tr><td>Hora:</td><td>{{ hora }}</td></tr>
		<tr><td>Proyecto:</td><td>{{ proyecto }}</td></tr>
	</table>

	</p>

</body>
</html>