<html>
<head>
	<meta charset="UTF-8">
	<title>{{ titulo }}</title>
</head>
<body>
	<p>Estimad@, {{ mensaje }}</p>

	<p>Detalles del proyecto:

	<table>
		<tr><td>Nombre:</td><td>{{ nombre }}</td></tr>
		<tr><td>Código:</td><td>{{ cod_proyecto }}</td></tr>
		<tr><td>Jefe proyecto:</td><td>{{ jefeproyecto }}</td></tr>
		<tr><td>Área:</td><td>{{ area }}</td></tr>
		<tr><td>Tecnología:</td><td>{{ tecnologia }}</td></tr>
	</table>

	</p>

</body>
</html>