<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title><?php print($this->config->appTitle)?></title>

	<meta name="description" content="<?php print($this->config->appTitle)?>">
	<meta name="author" content="<?php print($this->config->appAutor)?>">
	<meta name="theme-color" content="#1cabd1" />
	<meta name="robots" content="noindex, nofollow">

	<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

	<!-- Icons -->
	<!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
	<link rel="shortcut icon" href="assets/img/favicon.png">
	<link rel="apple-touch-icon" href="assets/img/icon57.png" sizes="57x57">
	<link rel="apple-touch-icon" href="assets/img/icon72.png" sizes="72x72">
	<link rel="apple-touch-icon" href="assets/img/icon76.png" sizes="76x76">
	<link rel="apple-touch-icon" href="assets/img/icon114.png" sizes="114x114">
	<link rel="apple-touch-icon" href="assets/img/icon120.png" sizes="120x120">
	<link rel="apple-touch-icon" href="assets/img/icon144.png" sizes="144x144">
	<link rel="apple-touch-icon" href="assets/img/icon152.png" sizes="152x152">
	<link rel="apple-touch-icon" href="assets/img/icon180.png" sizes="180x180">
	<!-- END Icons -->

	<!-- Stylesheets -->
	<!-- Bootstrap is included in its original form, unaltered -->
    <?php print($this->tag->stylesheetLink("css/bootstrap.min.css"))?>

	<!-- Related styles of various icon packs and plugins -->
    <?php print($this->tag->stylesheetLink("css/plugins.css"))?>

	<!-- The main stylesheet of this template. All Bootstrap overwrites are defined in here -->
    <?php print($this->tag->stylesheetLink("css/main.css"))?>

	<!-- The themes stylesheet of this template (for using specific theme color in individual elements - must included last) -->
    <?php print($this->tag->stylesheetLink("css/themes.css"))?>

    <!-- tema personalizado -->

    <?php print($this->tag->stylesheetLink("css/custom.css"))?>
	<!-- END Stylesheets -->

	<!-- calendario -->
	<?php print($this->tag->stylesheetLink("css/custom-timetable.css"))?>

	<?php
		if(isset($addCss)){
			foreach($addCss as $link){
				print($this->tag->stylesheetLink($link));
			}
		}
	?>
	
	<!-- Modernizr (browser feature detection library) & Respond.js (enables responsive CSS code on browsers that don't support it, eg IE8) -->
	<?php print($this->tag->javascriptInclude("js/vendor/modernizr-respond.min.js"))?>


</head>
<body class="page-loading">
		<div id="page-container" class="style-alt">
	        <!-- Main Container -->
	        <div id="main-container">

	            <header class="navbar navbar-default">
	                <?php if(isset($topMenu) && $topMenu==true) 
						echo $this->view->render('menu/main_menu_view',array('pcData'=>$pcData, 'menuSel' => $menuSel));
					?>
	            </header>
	            <!-- END Header -->

	            <!-- Page Content -->
	            <div id="page-content" class="clearfix" style="padding: 15px;">
	            	<div class="content-width">
		            <?php if(isset($pcView) && $pcView!=null) 
							echo $this->view->render($pcView,array('pcData'=>$pcData));
					?>
					</div>
	            </div>
	            <!-- END Page Content -->

	            <!-- Footer -->
	            <footer class="clearfix">
	                <div class="pull-right">
	                	<a href="<?php print($this->config->appAutorLink)?>" >Zenta Group</a>
	            	</div>
		            <div class="pull-left">
		               2016 &copy; <a href="<?php print($this->url->get())?>" target="_blank"><?php print($this->config->appName)?></a>
		            </div>
	            </footer>
	            <!-- END Footer -->
	        </div>
       		<!-- END Main Container -->

			<!-- Scroll to top link, initialized in js/app.js - scrollToTop() -->
			<a href="#" id="to-top"><i class="fa fa-angle-double-up"></i></a>
		</div>
    	<!-- END Page Container -->


	<!-- Remember to include excanvas for IE8 chart support -->
	<!--[if IE 8]><?php print($this->tag->javascriptInclude("js/helpers/excanvas.min.js"))?><![endif]-->

	<!-- jQuery, Bootstrap.js, jQuery plugins and Custom JS code -->
	<?php print($this->tag->javascriptInclude("js/vendor/jquery-1.11.3.min.js"))?>
	<?php print($this->tag->javascriptInclude("js/vendor/bootstrap.min.js"))?>
	<?php print($this->tag->javascriptInclude("js/plugins.js"))?>
	<script>
		var callAjax;
	</script>	
	<?php print($this->tag->javascriptInclude("js/mifaces.js"))?>
	<?php print($this->tag->javascriptInclude("js/app.js"))?>
	<?php print($this->tag->javascriptInclude("js/jquery.utilidades.js"))?>
	<?php print($this->tag->javascriptInclude("js/search.js"))?>
	<?php print($this->tag->javascriptInclude("js/vendor/jquery.doubleScroll.js"))?>

	<?php
	if(isset($jsScript) && $jsScript!=null){
	?>
	<script>
	<?php print($jsScript)?>
	</script>
	<?php
		}
	?>		
	<?php
		if(isset($addJs) && $addJs!=null){
			foreach($addJs as $link){
	?>
	<?php print($this->tag->javascriptInclude($link))?>
	<?php
			}
		}
	?>
	<?php
	if(isset($jsPosScrt) && $jsPosScrt!=null){
	?>
	<script>
	<?php print($jsPosScrt)?>
	</script>
	<?php
		}
	?>	


</body>
</html>